In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [11]:
da = pd.read_csv('../data/raw/test_transactions.csv', encoding='cp949')

da

,custid,sales_datetime,str_nm,goodcd,brd_nm,corner_nm,pc_nm,part_nm,team_nm,buyer_nm,import_flg,tot_amt,dis_amt,net_amt,inst_mon,inst_fee
0,30000,2017-05-17 19:00:00,본점,4405230126000,루츠,진케주얼,진케주얼,"케주얼,구두,아동",의류패션팀,유니캐주얼,0,47000,2350,44650,1,0
1,30000,2017-08-03 15:20:00,본점,4208200014400,제임스딘.P,내의,내의란제리,"케주얼,구두,아동",의류패션팀,니트단품,0,17500,880,16620,1,0
2,30000,2017-08-03 15:40:00,본점,4405600026000,퀵실버,진케주얼,진케주얼,"케주얼,구두,아동",의류패션팀,유니캐주얼,0,158000,7900,150100,1,0
3,30000,2017-08-06 16:20:00,본점,4405600026000,퀵실버,진케주얼,진케주얼,"케주얼,구두,아동",의류패션팀,유니캐주얼,0,-158000,-7900,-150100,1,0
4,30000,2017-08-06 16:20:00,본점,4405600026000,퀵실버,진케주얼,진케주얼,"케주얼,구두,아동",의류패션팀,유니캐주얼,0,148000,7400,140600,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
689772,49993,2018-01-31 17:50:00,신촌점,4405551020474,톰키드,아동,아동,아동문화,잡화가용팀,유아동복,0,20000,0,20000,1,0
689773,49993,2018-01-31 18:33:00,신촌점,2139140008300,폴로화장품,향수,화장품,패션잡화,잡화가용팀,화장품,0,70000,3500,66500,1,0
689774,49994,2018-04-14 17:50:00,본점,4230120011274,스테파넬,영트랜드,영트렌디,"케주얼,구두,아동",의류패션팀,영캐주얼,0,39000,0,39000,1,0
689775,49994,2018-04-14 18:10:00,본점,4409271026010,써스데이아일앤드,진케주얼,진케주얼,"케주얼,구두,아동",의류패션팀,유니캐주얼,0,34200,0,34200,1,0
689776,49994,2018-04-15 16:02:00,무역점,2116052008000,크리니크,수입종합화장품,화장품,명품잡화,잡화가용팀,화장품,1,86000,8600,77400,1,0

In [13]:
data = pd.read_csv('../data/raw/train_transactions.csv', encoding='cp949')

data

,custid,sales_datetime,str_nm,goodcd,brd_nm,corner_nm,pc_nm,part_nm,team_nm,buyer_nm,import_flg,tot_amt,dis_amt,net_amt,inst_mon,inst_fee
0,0,2017-06-25 12:12:00,무역점,2116050008000,에스티로더,수입종합화장품,화장품,명품잡화,잡화가용팀,화장품,1,90000,9000,81000,3,0
1,0,2017-06-25 12:42:00,무역점,4125440008000,시슬리,수입종합화장품,화장품,명품잡화,잡화가용팀,화장품,1,39000,3900,35100,1,0
2,0,2017-08-26 18:10:00,본점,2116052008000,크리니크,수입종합화장품,화장품,잡화파트,잡화가용팀,화장품,1,175000,17500,157500,3,0
3,0,2017-08-26 18:30:00,본점,4106430119900,듀퐁,수입의류,명품토탈,잡화파트,잡화가용팀,수입명품,1,455000,45500,409500,3,0
4,0,2017-09-03 18:02:00,무역점,2139141008000,랑콤,수입종합화장품,화장품,명품잡화,잡화가용팀,화장품,0,100000,10000,90000,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1036648,29998,2018-01-21 13:20:00,무역점,4241080013074,바닐라,영캐주얼,트랜디 케쥬얼,여성캐주얼,의류패션팀,영캐주얼,0,120000,0,120000,3,0
1036649,29998,2018-04-07 16:33:00,무역점,2139141008000,랑콤,수입종합화장품,화장품,명품잡화,잡화가용팀,화장품,0,38000,1900,36100,1,0
1036650,29999,2018-03-21 18:03:00,천호점,4109290004000,루이까또즈,핸드백,핸드백,잡화,잡화가용팀,피혁B,0,46000,2300,43700,1,0
1036651,29999,2018-03-29 18:23:00,천호점,4139350206500,소피에르핀,넥타이,셔츠,남성의류,의류패션팀,섬유,0,49000,2450,46550,1,0
1036652,29999,2018-04-21 13:13:00,천호점,4104840008000,샤넬,수입종합화장품,화장품,잡화,잡화가용팀,화장품,1,52000,2600,49400,1,0

In [17]:
target = pd.read_csv('../data/raw/y_train.csv', encoding='cp949')

target

       custid  gender
0           0       1
1           1       1
2           2       1
3           3       0
4           4       0
...       ...     ...
29995   29995       1
29996   29996       0
29997   29997       1
29998   29998       0
29999   29999       0

[30000 rows x 2 columns]